using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CRUD.Domain.Models
{
    public class Companies
    {
        public int Id { get; set; }
        public DateTime DateCreated { get; set; }
        public string Name { get; set; }
        public string TimeZone { get; set; }
        public string DefaultPassword { get; set; }
        public string CustomerTypes { get; set; }
        public string CustomerAccountTypes { get; set; }
        public string CustomCustomerFields { get; set; }
        public string ProjectStatusTypes { get; set; }
        public string CustomProjectFields { get; set; }
        public string ProjectConfidenceTypes { get; set; }
        public string CcType { get; set; }
        public string CcNumber { get; set; }
        public string CcName { get; set; }
        public string CcExpireMonth { get; set; }
        public string CcExpireYear { get; set; }
        public string CcCsc { get; set; }
        public string InventoryCategories { get; set; }
        public string FinePrint { get; set; }
        public string InventoryWorkArea { get; set; }
        public string InventoryWarehouses { get; set; }
        public string CustomInventoryFields { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string Industry { get; set; }
        public string UserGroups { get; set; }
        public string LineItemTaxCalculation { get; set; }
        public string WorkAreas { get; set; }
        public string Logo { get; set; }
        public string LeadSources { get; set; }
        public string AutoChangeStatus { get; set; }
        public string ShowCategoryWhenAddingLineItem { get; set; }
        public string InvoiceFinePrint { get; set; }
        public string ProjectShowContact { get; set; }
        public string Manufacturers { get; set; }
        public string ShowManufacturerWhenAddingLineItem { get; set; }
        public string EstimateColumns { get; set; }
        public string WorkOrderColumns { get; set; }
        public string InvoiceColumns { get; set; }
        public string UserGroupColors { get; set; }
        public string FilterAlwaysOpen { get; set; }
        public string EstimateCc { get; set; }
        public string WorkOrderCc { get; set; }
        public string InvoiceCc { get; set; }
        public string EstimateTypes { get; set; }
        public string WorkOrderTypes { get; set; }
        public string DefaultEstimateEmail { get; set; }
        public string DefaultWorkOrderEmail { get; set; }
        public string DefaultInvoiceEmail { get; set; }
        public string OpportunityActions { get; set; }
        public string ProjectTypes { get; set; }
        public string OpportunityTypes { get; set; }
        public string EstimateBcc { get; set; }
        public string WorkOrderBcc { get; set; }
        public string InvoiceBcc { get; set; }
        public string AccountingEmail { get; set; }
        public string UnitOfMeasures { get; set; }
        public string CustomerAcceptedEmail { get; set; }
        public string PurchaseOrderStatuses { get; set; }
        public string SalesGoal { get; set; }
        public string DefaultManufacturer { get; set; }
        public string DashboardName { get; set; }
        public string GoogleOuthRefreshToken { get; set; }
        public string GroupedInventoryView { get; set; }
        public string GoogleCalendarId { get; set; }
        public string LeadStatusTypes { get; set; }
        public string DefaultEventColor { get; set; }
        public string DefaultEventTextColor { get; set; }
        public string TrackableAssetTypes { get; set; }
        public string LostReasons { get; set; }
        public string TrackingApplicationId { get; set; }
        public string TrackingSecretKey { get; set; }
        public string FieldGrooveBrand { get; set; }
        public string MasterDemoAccount { get; set; }
        public string DemoAccount { get; set; }
        public string BarColor { get; set; }
        public string PaymentMethodPreview { get; set; }
        public string Token { get; set; }
        public string UserRate { get; set; }
        public string InstallerRate { get; set; }
        public string EmailReceipt { get; set; }
        public string PaymentAddress1 { get; set; }
        public string PaymentAddress2 { get; set; }
        public string PaymentCity { get; set; }
        public string PaymentState { get; set; }
        public string PaymentZip { get; set; }
        public string PaymentPhone { get; set; }
        public string PaymentFirstName { get; set; }
        public string PaymentLastName { get; set; }
        public string Number { get; set; }
        public string Phases { get; set; }
        public string InstallerPaySchedule { get; set; }
        public string DefaultGroupsToAssets { get; set; }
        public string TrackingApplicationProvider { get; set; }
        public string TrackingApplicationUsername { get; set; }
        public string TrackingApplicationPassword { get; set; }
        public string SignedCustomerEmailSubject { get; set; }
        public string SignedCustomerEmailMessage { get; set; }
        public string IframeEnabled { get; set; }
        public string IframeCustomCss { get; set; }
        public string IframeBackgroundColor { get; set; }
        public string IframeTextColor { get; set; }
        public string IframeButtonColor { get; set; }
        public string IframeSuccessMessage { get; set; }
        public string IframeDefaultEmail { get; set; }
        public string DisableBilling { get; set; }
        public string DisplayLaborOnWorkOrderByDefault { get; set; }
        public string MonthlyBillingCap { get; set; }
        public string AutoRoundPricing { get; set; }
        public string SmsHoursPrior { get; set; }
        public string SmsText { get; set; }
        public DateTime DateModified { get; set; }
        public string ConvenienceFeeRate { get; set; }
        public DateTime BillingStartDate { get; set; }
        public string SmsHourOfDay { get; set; }
        public string SmsSetting { get; set; }
        public string SubMerchantId { get; set; }
        public string SubMerchantAccountPreview { get; set; }
        public string SubMerchantRate { get; set; }
        public string PageBreakBeforeFinePrint { get; set; }
        public string PageBreakBeforeLoadTicket { get; set; }
        public string PercentageOfLaborOnWorkOrder { get; set; }
        public string HidePhaseTotals { get; set; }
        public string HideEstimateTotals { get; set; }
        public string GlCategories { get; set; }
        public string HouseAccountSalesCommissionRate { get; set; }
        public string HouseAccountEstimatorCommissionRate { get; set; }
        public string HouseAccountProjectManagementCommissionRate { get; set; }
        public string AutoMarkLostDays { get; set; }
        public string ShowContactOnEstimate { get; set; }
        public string ProposalAcceptanceText { get; set; }
        public string CalendarStartDay { get; set; }
        public string InvoiceEmailSubject { get; set; }
        public string TaxSubtotal { get; set; }
        public string DisableAutoInProgress { get; set; }
        public string EvenlySpacePrintableColumns { get; set; }
        public string DisableAbilityToDuplicateWorkOrders { get; set; }
        public string DisableCalendarRefresh { get; set; }
        public string EnforceUniqueLogins { get; set; }
        public string LostReasons2 { get; set; }
        public string ContactCustomTypes { get; set; }
        public string QbToken { get; set; }
        public string QbRefreshToken { get; set; }
        public DateTime QbLastTokenRefreshDate { get; set; }
        public string QbRealmId { get; set; }
        public string QbError { get; set; }
        public string DefaultQuickbooksIncomeAccountId { get; set; }
        public string DefaultQuickbooksTaxCodeId { get; set; }
        public string DefaultQuickbooksExpenseAccountId { get; set; }
        public string DefaultQuickbooksTaxRateId { get; set; }
        public DateTime QuickbooksSyncAfterDate { get; set; }
        public string CompleteEventColor { get; set; }
        public string AllowInvoiceBeforeWorkOrderComplete { get; set; }
        public string EnableAutoClose { get; set; }
        public string EnableQuickbooksCustomers { get; set; }
        public string EnableQuickbooksVendors { get; set; }
        public string EnableQuickbooksProducts { get; set; }
        public string EnableQuickbooksInvoices { get; set; }
        public string EnableQuickbooksPayments { get; set; }
        public string EnableAutoArchive { get; set; }
        public string AllowDifficultyLevel { get; set; }
        public string DoNotAllowLineItemNameChange { get; set; }
        public string EnableSlidingScaleCommissions { get; set; }
        public string HideEstimateTaxTotal { get; set; }
        public string HideEstimateSubTotal { get; set; }
        public string EnableQuickbooksTwoWaySync { get; set; }
        public string DefaultOnlyShowPhaseTotal { get; set; }
        public string ShowTermsOnInvoice { get; set; }
        public string CollapseBaseEstimateByDefault { get; set; }
        public string CustomerRequiredFields { get; set; }
        public string QuickbooksAssetAccountId { get; set; }
        public string DisplaySalesPhoneAndEmail { get; set; }
        public string ShowTermsOnEstimate { get; set; }
        public string NotifyAccountingByDefault { get; set; }
        public string NotifySalespersonByDefault { get; set; }
        public string RemoveDefaultWorkOrderForm { get; set; }
        public string DisplayToolListOnWorkOrder { get; set; }
        public string DisplayInstallerFormOnWorkOrder { get; set; }
        public string YesOrNoQuestions { get; set; }
        public string WorkOrderTools { get; set; }
        public string FieldInvoiceColumns { get; set; }
        public string EnableQuickbooksDeposits { get; set; }
        public string IncludeCustomerAcceptanceOnWorkOrder { get; set; }
        public string ProjectEstimateDetails { get; set; }
        public string CustomerAcceptanceText { get; set; }
        public string NumberOfEmptyLines { get; set; }
        public string HideLoadTicketFromWO { get; set; }
        public string HideInstallersNamesOnWO { get; set; }
        public string AllowEstimateInvoice { get; set; }
        public string InstallerFormColumns { get; set; }
        public string ShowTaxInPhaseAndSubTotal { get; set; }
        public string EnableQuickbooksDesktopCustomers { get; set; }
        public string EnableQuickbooksDesktopVendors { get; set; }
        public string EnableQuickbooksDesktopProducts { get; set; }
        public string EnableQuickbooksDesktopInvoices { get; set; }
        public string EnableQuickbooksDesktopPayments { get; set; }
        public string EnableQuickbooksDesktopTwoWaySync { get; set; }
        public DateTime QuickbooksDesktopSyncAfterDate { get; set; }
        public string UseNewInvoiceReportLayout { get; set; }
        public string CustomerAccountTypeIds { get; set; }
        public string IsLocked { get; set; }
        public string AllowToSendEmail { get; set; }
        public string DefaultQuickbooksDesktopIncomeAccountId { get; set; }
        public string DefaultQuickbooksDesktopExpenseAccountId { get; set; }
        public string QuickbooksDesktopAssetAccountId { get; set; }
        public string IframeLocationIds { get; set; }
    }
}
